{$DEFINE DEBUG} // Debug mode (Режим отладки)
//{$DEFINE SERVICE} // SERVICE mode (Режим службы)

{*
 * CLIENTS (Клиенты)
 *}
//{$DEFINE GridCom} // Select company (Выбрать организацию)
{$DEFINE Nazir} // Select company (Выбрать организацию)
//{$DEFINE OVVIO} // Select company (Выбрать организацию)

{*
 * EXTRA  (Дополнительно)
 *}
//{$DEFINE APP_ALREADY_RANNING} //
{$DEFINE PARUS} // Work with Parus Работа с КИСУ "Парус"
//Mainstream support - Общая поддержка
//Extended support - Расширенная поддержка

{*
 * SECURITY  (Безопасность)
 *}
{$DEFINE LOGIN}     // Login (Запрос пароля)
//{$DEFINE PASSWORD_PROTECT}     // Password protect (Защита пароля (шифорование))
//{$DEFINE LOGIN_PROTECT}     // Login protect (Защита ввода пароля)

//{$DEFINE PROTECT} // Защита программы - убрать {$DEFINE DEMO} и {$DEFINE PROTECT_LITE} и {$DEFINE PROTECT_HDD}!!!!
//{$DEFINE PROTECT_LITE} // Упрощённая защита программы - убрать {$DEFINE DEMO} и {$DEFINE PROTECT} и {$DEFINE PROTECT_HDD}!!!!
//{$DEFINE PROTECT_HDD} // Защита программы жесткий диск (только для Windows XP) - убрать {$DEFINE DEMO} и {$DEFINE PROTECT_LITE} и {$DEFINE PROTECT} !!!!

//{$DEFINE TIMER}   // Date limitation (Ограничение по дате)
//{$DEFINE DEMO}    // Demo version (Демо версия программы)

{*
 * LANGUAGE  (Язык)
 *}
//{$DEFINE LANG_RU_RU}   // Language (Язык)
{$DEFINE LANG_EN_EN}   // Language

